# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
    adapter: postgresql
    encoding: unicode
    host: localhost
    pool: 5
    username: atmta
    password: granata43



development:
  <<: *default
  database: kurs_p_development

test:
  <<: *default
  database: kurs_p__test

production:
  host: ec2-54-83-25-238.compute-1.amazonaws.com
  database: dfomgi1pn3rv47
  username: kfftrrzcocyoam
  password: o44zzZz7_FsD2-Zh08nxVNRGFs

